### ISSUE TITLE
Solarmach forces matplotlib==3.5.3

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/pyhc-docker-environment#10]
Solarmach has a requirement `matplotlib==3.5.3`. This is too low of a version for some packages (e.g. pySPEDAS which needs at least 3.6.2).

I opened an [issue in the solarmach repo](https://github.com/jgieseler/Solar-MACH/issues/27) asking them to loosen the requirement.

**Comment by jgieseler** [comment]
Fixed with https://github.com/jgieseler/solarmach/releases/tag/v0.4.0
